---
title: "Assignment 5"
author: "Gracie White"
date: "November 29, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
##Load Packages and Read in the Data 

library(tidyverse)
library(stargazer)
library(kableExtra)

fac_sal_df <- read_csv("Faculty salary data (2008 - 2009 survey).csv")
grad_enroll_df <- read_csv("Grad Enrollment.csv")
phd_med_sal_df <- read_csv("Median salary for doctoral recipients.csv")
phd_field_df <- read_csv("PhDs by Field 1985 - 2015.csv")
enroll_tidy_df <- read_csv("enrollment tidy.csv")
female_phd_tidy <- read_csv("Female_phds.csv")
female_probtable <- read_csv("phd_proptable.csv")

```


Question 1: Male and Female Graduate Enrollment (1967-2015)
```{r}
# Exploring the data

enroll_explore <- ggplot(enroll_tidy_df, aes(x = Year, y = Enrollment)) +
  geom_point(aes(color = Sex))

enroll_explore



# Female enrollment looks to be increasing at a much faster rate than male enrollment. Male enrollment was initially higher, but in the late 1980's, female enrollment surpassed male enrollement. Both enrollments level out at 2010. Male enrollment goes through stagnant periods and short spurts of increasing.


# Running a linear regression on dependent variable (y = male enrollment) by independent variale (x = year)

enroll_male_lm1 <- lm(`total Males` ~ Year, data = grad_enroll_df)

summary(enroll_male_lm1)

plot(enroll_male_lm1)

# Running a linear regression on dependent variable (y = female enrollment) by independent variable (x = year)

enroll_female_lm1 <- lm(`total Females` ~ Year, data = grad_enroll_df)

summary(enroll_female_lm1)

plot(enroll_female_lm1)

# To show the trends graphically, we will plot a graph over time of female and male enrollment to show the differences in trends.

grad_enroll_graph <- ggplot(enroll_tidy_df, aes(x = Year, y = Enrollment)) +
  geom_line(aes(color = Sex), size = 1) +
  theme_linedraw() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0), breaks = seq(0, 2000000, 250000), limits = c(0,2000000)) +
  labs(x = "Year", y = "Total Graduate Enrollment", title ="Graduate Enrollment in the United States (1967-2015)")

grad_enroll_graph
```


Question 2: Shifts in Female PhD Recipients by Field (1985,2000,2015)
```{r}

#Describe if and how there was a shift in PhDs awarded to females in four fields (Physical and Earth Sciences, Engineering, Education, and Humanities & Arts) in 1985, 2000, and 2015. Describe your results statistically, in a graph or table, and in text. 
#Tried to make a dataframe to graph the trends.. this was attempt 1:
phd_female_fields <- phd_field_df %>% 
  select("Field of study and sex", "Gender", "Number 1985", "Percent 1985", "Number 2000", "Percent 2000", "Number 2015", "Percent 2015") %>% 
  filter(Gender == "Female", `Field of study and sex` == "Physical sciences and earth sciences" | `Field of study and sex` == "Engineering" | `Field of study and sex` == "Education" | `Field of study and sex` == "Humanities and arts")
#but realized it was in a terrible format that R couldn't deal with so went back into excel and made a new one
#Attempt 2:

#reassign year to be a character

female_phd_tidy$Year <- as.character(female_phd_tidy$Year)

phd_female_number_graph <- ggplot(female_phd_tidy, aes(x = Year, y = `Number Enrolled`, group = `Field of study and sex`)) +
  geom_col(position = "dodge", aes(fill = `Field of study and sex`)) + 
  theme_classic() + 
  scale_y_continuous(expand = c(0,0)) + 
  scale_fill_discrete(name = "Field of Study")
  
phd_female_number_graph

#Does this make sense, or is it better to group by year??? 

#ok making another one that's based on percents  

phd_female_percent_graph <- ggplot(female_phd_tidy, aes(x = Year, y = `Percent Enrolled`, group = `Field of study and sex`)) +
  geom_col(position = "dodge", aes(fill = `Field of study and sex`)) +
   theme_classic() + 
  scale_fill_discrete(name = "Field of Study")
  
phd_female_percent_graph

#proptables and chi square

female_probtable$`1985`$`2000`$`2015` <- factor(female_probtable$`1985`$`2000`$`2015`)

phd_prop <- prop.table(as.matrix(female_probtable), 1)
phd_prop
```


Question 3: Male and Female Salaries for Starting PostDoc & Other Employment Positions
```{r}
phd_med <- phd_med_sal_df %>% 
  filter(Employment != "Male")
View(phd_med)

phd_med$Employment <- factor(phd_med$Employment)
phd_med$X3 <- factor(phd_med$X3)
phd_med$`Postdoctoral study` <- factor(phd_med$`Postdoctoral study`)
phd_med$X5 <- factor(phd_med$X5)

# Running paired t-tests for the median salaries of male and females

# Regular employment

employment_t <- t.test(phd_med$Employment, phd_med$X3, paired = TRUE, data = phd_med)

# It doesn't work! need to do mann whitney U

<<<<<<< HEAD
phd_med_sal_tidy_df

employment_t <- t.test()
```
```{r}
# Question 3

# Exploratory Analysis

# Make histogram of median salary vs sex, Employment
employment_test_df <- phd_med_sal_tidy_df %>% 
  filter(Planas == "EMPLOYMENT")

employment_test_hist <- ggplot(employment_test_df, aes(x = Median.Salary )) +
  geom_histogram(bins = 6, aes(fill = Sex)) +
  facet_wrap(~ Sex, scale = "free") +
  theme_classic() +
  theme(legend.position = "none") + 
  scale_y_continuous(expand = c(0,0))

employment_test_hist

# Make histogram of median salary vs sex, Employment
postdoc_test_df <- phd_med_sal_tidy_df %>% 
  filter(Planas == "POSTDOC")

postdoc_test_hist <- ggplot(postdoc_test_df, aes(x = Median.Salary )) +
  geom_histogram(bins = 6, aes(fill = Sex)) +
  facet_wrap(~ Sex, scale = "free") +
  theme_classic() +
  theme(legend.position = "none") + 
  scale_y_continuous(expand = c(0,0))

postdoc_test_hist

=======
employment_mannu <- 
>>>>>>> c7759487c4160cce9f0a2562fc3e9020ef695c7b
```


Question 4: Exploring Academic Salaries for Professors in U.S. Colleges
```{r}

```

